// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Brandon Huey <hello@aftertone.co>

//! Granular synthesis oscillator — clouds of micro-oscillator grains.
//!
//! Each grain is a short burst of waveform (1-500ms) generated by a
//! `PhaseOscillator` with morphable shape (sine→tri→saw→square).
//! Grains spawn continuously while the voice is active; the voice's
//! amp envelope gates the entire cloud.

use std::f32::consts::TAU;

use brume_common::ParameterId;
use brume_dsp_core::{PhaseOscillator, Smoother, morph_wave};

use crate::oscillator_core::Engine;

const MAX_GRAINS: usize = 32;
const SMOOTHER_MS: f32 = 10.0;

/// Individual grain state.
struct Grain {
    osc: PhaseOscillator,
    position: u32,
    length: u32,
    amplitude: f32,
    pitch_ratio: f32,
    morph: f32,
    pan: f32,
    active: bool,
}

impl Grain {
    fn new(sample_rate: f32) -> Self {
        Self {
            osc: PhaseOscillator::new(sample_rate),
            position: 0,
            length: 0,
            amplitude: 1.0,
            pitch_ratio: 1.0,
            morph: 0.0,
            pan: 0.0,
            active: false,
        }
    }
}

/// Granular synthesis oscillator.
///
/// Generates pitched grain clouds from overlapping micro-oscillators.
/// 32-grain pool with round-robin recycling. Zero allocation on the audio thread.
pub struct GranularOscillator {
    grains: [Grain; MAX_GRAINS],
    samples_until_spawn: f32,
    next_grain_idx: usize,
    active_grain_count: u32,

    density: Smoother,
    grain_size: Smoother,
    morph: Smoother,
    scatter: Smoother,
    spread: Smoother,
    drift: Smoother,
    fm_depth: Smoother,
    fm_ratio: Smoother,
    grain_position: Smoother,
    grain_shape: Smoother,

    fm_osc: PhaseOscillator,
    norm_gain: Smoother, // Smoothed 1/sqrt(n) to prevent clicks
    drift_phase: f32,
    drift_value: f32,
    rng_state: u32,
    base_frequency: f32,
    sample_rate: f32,
}

impl GranularOscillator {
    /// Creates a new granular oscillator.
    #[must_use]
    pub fn new(sample_rate: f32) -> Self {
        let grains = std::array::from_fn(|_| Grain::new(sample_rate));
        Self {
            grains,
            samples_until_spawn: 0.0,
            next_grain_idx: 0,
            active_grain_count: 0,

            density: Smoother::new(0.3, SMOOTHER_MS, sample_rate),
            grain_size: Smoother::new(0.2, SMOOTHER_MS, sample_rate),
            morph: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            scatter: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            spread: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            drift: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            fm_depth: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            fm_ratio: Smoother::new(2.0, SMOOTHER_MS, sample_rate),
            grain_position: Smoother::new(0.0, SMOOTHER_MS, sample_rate),
            grain_shape: Smoother::new(0.0, SMOOTHER_MS, sample_rate),

            fm_osc: PhaseOscillator::new(sample_rate),
            norm_gain: Smoother::new(1.0, 5.0, sample_rate),
            drift_phase: 0.0,
            drift_value: 0.0,
            rng_state: 0xDEAD_BEEF,
            base_frequency: 440.0,
            sample_rate,
        }
    }

    /// Sets the base frequency (called by voice on note_on).
    pub fn set_frequency(&mut self, freq: f32) {
        self.base_frequency = freq;
        self.fm_osc.set_frequency(freq * self.fm_ratio.value());
    }

    // ── Parameter setters ──

    pub fn set_density(&mut self, v: f32) {
        self.density.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_grain_size(&mut self, v: f32) {
        self.grain_size.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_morph(&mut self, v: f32) {
        self.morph.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_scatter(&mut self, v: f32) {
        self.scatter.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_spread(&mut self, v: f32) {
        self.spread.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_drift(&mut self, v: f32) {
        self.drift.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_fm_depth(&mut self, v: f32) {
        self.fm_depth.set_target(v.clamp(0.0, 10.0));
    }
    pub fn set_fm_ratio(&mut self, v: f32) {
        self.fm_ratio.set_target(v.clamp(0.5, 16.0));
    }
    pub fn set_position(&mut self, v: f32) {
        self.grain_position.set_target(v.clamp(0.0, 1.0));
    }
    pub fn set_grain_shape(&mut self, v: f32) {
        self.grain_shape.set_target(v.clamp(0.0, 1.0));
    }

    // ── RNG (xorshift, same pattern as GranularTransient) ──

    #[inline]
    fn random(&mut self) -> f32 {
        self.rng_state ^= self.rng_state << 13;
        self.rng_state ^= self.rng_state >> 17;
        self.rng_state ^= self.rng_state << 5;
        (self.rng_state as f32) / (u32::MAX as f32)
    }

    #[inline]
    fn random_bipolar(&mut self) -> f32 {
        self.random() * 2.0 - 1.0
    }

    // ── Grain envelope ──

    /// Computes the grain envelope value for a given progress (0-1) and shape.
    #[inline]
    fn grain_envelope(progress: f32, shape: f32) -> f32 {
        let hann = 0.5 * (1.0 - (progress * TAU).cos());
        if shape <= 0.5 {
            // Hann → Gaussian
            let t = shape * 2.0;
            let gaussian = (-18.0 * (progress - 0.5) * (progress - 0.5)).exp();
            hann * (1.0 - t) + gaussian * t
        } else {
            // Gaussian → Trapezoid
            let t = (shape - 0.5) * 2.0;
            let gaussian = (-18.0 * (progress - 0.5) * (progress - 0.5)).exp();
            let trap = (progress * 10.0).min(1.0).min((1.0 - progress) * 10.0);
            gaussian * (1.0 - t) + trap * t
        }
    }

    // ── Grain spawning ──

    fn spawn_grain(&mut self) {
        let scatter = self.scatter.value();
        let drift_amt = self.drift.value();
        let morph = self.morph.value();
        let pos = self.grain_position.value();
        let spread = self.spread.value();
        let size_norm = self.grain_size.value();

        // Pitch: scatter randomizes ±2 octaves
        let pitch_rand = self.random_bipolar();
        let pitch_ratio = (2.0_f32).powf(pitch_rand * scatter * 2.0);
        let freq = self.base_frequency * pitch_ratio * (1.0 + self.drift_value * drift_amt);
        let freq = freq.clamp(20.0, self.sample_rate * 0.49);

        // Grain length: 1-500ms mapped from normalized size
        let size_ms = 1.0 + size_norm * 499.0;
        let jitter = 1.0 + self.random_bipolar() * 0.2;
        let length_samples = ((size_ms * jitter) * self.sample_rate / 1000.0) as u32;
        let length_samples = length_samples.max(1);

        // Start phase: position + scatter jitter
        let phase_jitter = self.random_bipolar() * 0.1 * scatter;
        let start_phase = (pos + phase_jitter).rem_euclid(1.0);

        // Pan
        let pan = self.random_bipolar() * spread;

        // Steal slot via round-robin
        if self.grains[self.next_grain_idx].active {
            self.active_grain_count = self.active_grain_count.saturating_sub(1);
        }

        let grain = &mut self.grains[self.next_grain_idx];
        grain.osc.set_frequency(freq);
        grain.osc.set_phase(start_phase);
        grain.position = 0;
        grain.length = length_samples;
        grain.amplitude = 1.0;
        grain.pitch_ratio = pitch_ratio;
        grain.morph = morph;
        grain.pan = pan;
        grain.active = true;

        self.next_grain_idx = (self.next_grain_idx + 1) % MAX_GRAINS;
        self.active_grain_count += 1;
    }

    /// Processes one sample of granular output.
    #[inline]
    pub fn process(&mut self) -> f32 {
        // Advance smoothers
        let density = self.density.process();
        let _grain_size = self.grain_size.process();
        let _morph = self.morph.process();
        let _scatter = self.scatter.process();
        let _spread = self.spread.process();
        let drift_amt = self.drift.process();
        let fm_depth = self.fm_depth.process();
        let fm_ratio = self.fm_ratio.process();
        let _position = self.grain_position.process();
        let shape = self.grain_shape.process();

        // Update FM oscillator frequency
        self.fm_osc.set_frequency(self.base_frequency * fm_ratio);
        let fm_sample = self.fm_osc.sine();
        self.fm_osc.advance();

        // Advance drift (slow random walk ~0.3 Hz)
        if drift_amt > 0.001 {
            self.drift_phase += 0.3 / self.sample_rate;
            if self.drift_phase >= 1.0 {
                self.drift_phase -= 1.0;
                // Step the random walk
                self.drift_value += self.random_bipolar() * 0.02;
                self.drift_value = self.drift_value.clamp(-0.5, 0.5);
            }
        }

        // Spawn check
        self.samples_until_spawn -= 1.0;
        if self.samples_until_spawn <= 0.0 {
            self.spawn_grain();
            // Density: 0-1 maps to 1-200 grains/sec
            let density_hz = 1.0 + density * 199.0;
            let interval = self.sample_rate / density_hz;
            let jitter = 1.0 + self.random_bipolar() * 0.3;
            self.samples_until_spawn += (interval * jitter).max(1.0);
        }

        // Sum active grains
        let mut sum = 0.0_f32;
        let mut active = 0_u32;
        let pm = fm_depth * fm_sample * TAU;

        for grain in &mut self.grains {
            if !grain.active {
                continue;
            }

            let progress = grain.position as f32 / grain.length as f32;
            let envelope = Self::grain_envelope(progress, shape);
            let sample = morph_wave(grain.osc.phase(), pm, grain.morph);

            sum += sample * envelope * grain.amplitude;
            active += 1;

            grain.osc.advance();
            grain.position += 1;
            if grain.position >= grain.length {
                grain.active = false;
            }
        }

        // Update cached count
        self.active_grain_count = active;

        // Smooth normalization gain to prevent clicks when grain count changes
        let target_gain = if active > 1 {
            1.0 / (active as f32).sqrt()
        } else {
            1.0
        };
        self.norm_gain.set_target(target_gain);
        let gain = self.norm_gain.process();

        sum * gain
    }

    /// Soft reset — lets active grains ring out through their envelopes.
    /// Only resets spawn timing and drift so new grains use the new frequency.
    pub fn reset(&mut self) {
        self.samples_until_spawn = 0.0;
        self.drift_value = 0.0;
        self.drift_phase = 0.0;
        self.fm_osc.reset();
        // Re-seed RNG for fresh grain scatter on the new note
        self.rng_state = self
            .rng_state
            .wrapping_mul(1_103_515_245)
            .wrapping_add(12345);
    }
}

impl Engine for GranularOscillator {
    fn set_parameter(&mut self, id: ParameterId, value: f32) {
        match id {
            ParameterId::GranularDensity => self.set_density(value),
            ParameterId::GranularGrainSize => self.set_grain_size(value),
            ParameterId::GranularMorph => self.set_morph(value),
            ParameterId::GranularScatter => self.set_scatter(value),
            ParameterId::GranularSpread => self.set_spread(value),
            ParameterId::GranularDrift => self.set_drift(value),
            ParameterId::GranularFmDepth => self.set_fm_depth(value),
            ParameterId::GranularFmRatio => self.set_fm_ratio(value),
            ParameterId::GranularPosition => self.set_position(value),
            ParameterId::GranularGrainShape => self.set_grain_shape(value),
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SR: f32 = 48000.0;

    #[test]
    fn produces_output_at_defaults() {
        let mut osc = GranularOscillator::new(SR);
        osc.set_frequency(440.0);
        let mut has_output = false;
        for _ in 0..4800 {
            if osc.process().abs() > 0.001 {
                has_output = true;
                break;
            }
        }
        assert!(has_output, "should produce non-zero output");
    }

    #[test]
    fn output_bounded() {
        let mut osc = GranularOscillator::new(SR);
        osc.set_frequency(220.0);
        osc.set_density(1.0);
        osc.set_grain_size(0.5);
        osc.set_scatter(1.0);
        osc.set_morph(0.5);
        osc.set_fm_depth(5.0);

        for _ in 0..48000 {
            let s = osc.process();
            assert!(s.is_finite(), "output must be finite");
            assert!(s.abs() < 3.0, "output must be bounded, got {s}");
        }
    }

    #[test]
    fn density_affects_grain_count() {
        // Low density
        let mut low = GranularOscillator::new(SR);
        low.set_frequency(440.0);
        low.set_density(0.05);
        for _ in 0..24000 {
            let _ = low.process();
        }
        let low_count = low.active_grain_count;

        // High density
        let mut high = GranularOscillator::new(SR);
        high.set_frequency(440.0);
        high.set_density(1.0);
        high.set_grain_size(0.8);
        for _ in 0..24000 {
            let _ = high.process();
        }
        let high_count = high.active_grain_count;

        assert!(
            high_count > low_count,
            "high density ({high_count}) should have more active grains than low ({low_count})"
        );
    }

    #[test]
    fn scatter_changes_spectrum() {
        fn count_crossings(osc: &mut GranularOscillator, samples: usize) -> usize {
            let mut crossings = 0;
            let mut prev = 0.0;
            for _ in 0..samples {
                let s = osc.process();
                if s * prev < 0.0 {
                    crossings += 1;
                }
                prev = s;
            }
            crossings
        }

        let mut unison = GranularOscillator::new(SR);
        unison.set_frequency(440.0);
        unison.set_scatter(0.0);
        unison.set_density(0.5);
        // Warm up
        for _ in 0..4800 {
            let _ = unison.process();
        }
        let c1 = count_crossings(&mut unison, 24000);

        let mut scattered = GranularOscillator::new(SR);
        scattered.set_frequency(440.0);
        scattered.set_scatter(1.0);
        scattered.set_density(0.5);
        for _ in 0..4800 {
            let _ = scattered.process();
        }
        let c2 = count_crossings(&mut scattered, 24000);

        // With scatter, crossing count should differ (more chaotic)
        assert!(
            c1 != c2,
            "scatter should change spectral content: unison={c1}, scattered={c2}"
        );
    }

    #[test]
    fn morph_changes_waveform() {
        fn rms_energy(osc: &mut GranularOscillator, samples: usize) -> f32 {
            let mut sum_sq = 0.0;
            for _ in 0..samples {
                let s = osc.process();
                sum_sq += s * s;
            }
            (sum_sq / samples as f32).sqrt()
        }

        let mut sine = GranularOscillator::new(SR);
        sine.set_frequency(440.0);
        sine.set_morph(0.0);
        sine.set_density(0.8);
        sine.set_grain_size(0.5);
        for _ in 0..4800 {
            let _ = sine.process();
        }
        let e1 = rms_energy(&mut sine, 24000);

        let mut square = GranularOscillator::new(SR);
        square.set_frequency(440.0);
        square.set_morph(1.0);
        square.set_density(0.8);
        square.set_grain_size(0.5);
        for _ in 0..4800 {
            let _ = square.process();
        }
        let e2 = rms_energy(&mut square, 24000);

        // Square grains have more energy than sine grains
        assert!(
            e2 > e1 * 1.05,
            "square morph ({e2:.4}) should have more energy than sine ({e1:.4})"
        );
    }

    #[test]
    fn grain_pool_recycles_without_crash() {
        let mut osc = GranularOscillator::new(SR);
        osc.set_frequency(440.0);
        osc.set_density(1.0);
        osc.set_grain_size(1.0); // 500ms grains, will fill pool

        for _ in 0..96000 {
            let s = osc.process();
            assert!(s.is_finite());
        }
    }

    #[test]
    fn soft_reset_preserves_grains() {
        let mut osc = GranularOscillator::new(SR);
        osc.set_frequency(440.0);
        for _ in 0..4800 {
            let _ = osc.process();
        }
        let count_before = osc.active_grain_count;
        assert!(count_before > 0);

        osc.reset();
        // Grains still active after soft reset
        assert!(osc.active_grain_count > 0);
    }

    #[test]
    fn fm_adds_harmonics() {
        fn count_crossings(osc: &mut GranularOscillator, samples: usize) -> usize {
            let mut crossings = 0;
            let mut prev = 0.0;
            for _ in 0..samples {
                let s = osc.process();
                if s * prev < 0.0 {
                    crossings += 1;
                }
                prev = s;
            }
            crossings
        }

        let mut dry = GranularOscillator::new(SR);
        dry.set_frequency(440.0);
        dry.set_fm_depth(0.0);
        dry.set_density(0.8);
        dry.set_grain_size(0.5);
        for _ in 0..4800 {
            let _ = dry.process();
        }
        let c1 = count_crossings(&mut dry, 24000);

        let mut fm = GranularOscillator::new(SR);
        fm.set_frequency(440.0);
        fm.set_fm_depth(5.0);
        fm.set_fm_ratio(3.0);
        fm.set_density(0.8);
        fm.set_grain_size(0.5);
        for _ in 0..4800 {
            let _ = fm.process();
        }
        let c2 = count_crossings(&mut fm, 24000);

        assert!(c2 > c1, "FM should add harmonic content: dry={c1}, fm={c2}");
    }

    #[test]
    fn all_features_simultaneously() {
        let mut osc = GranularOscillator::new(SR);
        osc.set_frequency(220.0);
        osc.set_density(0.7);
        osc.set_grain_size(0.4);
        osc.set_morph(0.5);
        osc.set_scatter(0.5);
        osc.set_spread(0.8);
        osc.set_drift(0.5);
        osc.set_fm_depth(3.0);
        osc.set_fm_ratio(2.5);
        osc.set_position(0.3);
        osc.set_grain_shape(0.5);

        for _ in 0..48000 {
            let s = osc.process();
            assert!(s.is_finite() && s.abs() < 4.0, "got {s}");
        }
    }

    #[test]
    fn grain_envelope_shapes() {
        // Hann peaks at center
        let hann_mid = GranularOscillator::grain_envelope(0.5, 0.0);
        let hann_edge = GranularOscillator::grain_envelope(0.0, 0.0);
        assert!(hann_mid > 0.9);
        assert!(hann_edge < 0.01);

        // Gaussian peaks at center
        let gauss_mid = GranularOscillator::grain_envelope(0.5, 0.5);
        assert!(gauss_mid > 0.9);

        // Trapezoid has flat sustain
        let trap_quarter = GranularOscillator::grain_envelope(0.25, 1.0);
        let trap_mid = GranularOscillator::grain_envelope(0.5, 1.0);
        assert!(
            (trap_quarter - trap_mid).abs() < 0.01,
            "trapezoid should be flat in middle"
        );
    }
}
