[package]
name = "brume-app-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
brume-common = { path = "../common" }
brume-modulation = { path = "../modulation" }
serde = { workspace = true }

[lints]
workspace = true
